# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from connectWindow import Ui_connectWindow
from aboutWindow import Ui_aboutWindow
from setup import searchFile, deleteFile


class Ui_mainWindow(object):
    def openConnectWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_connectWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAboutWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_aboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.resize(800, 600)
        scriptDir = os.path.dirname(os.path.realpath(__file__))
        mainWindow.setWindowIcon(QtGui.QIcon(
            scriptDir + '/resources/logo.png'))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(800, 600))
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(360, 520, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirmButton.setFont(font)
        self.confirmButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confirmButton.setObjectName("confirmButton")
        self.itemName = QtWidgets.QLineEdit(self.centralwidget)
        self.itemName.setGeometry(QtCore.QRect(130, 440, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.itemName.setFont(font)
        self.itemName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.itemName.setAcceptDrops(False)
        self.itemName.setObjectName("itemName")
        self.itemURL = QtWidgets.QLineEdit(self.centralwidget)
        self.itemURL.setGeometry(QtCore.QRect(130, 480, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.itemURL.setFont(font)
        self.itemURL.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.itemURL.setAcceptDrops(False)
        self.itemURL.setObjectName("itemURL")
        self.validateButton = QtWidgets.QPushButton(self.centralwidget)
        self.validateButton.setGeometry(QtCore.QRect(200, 520, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.validateButton.setFont(font)
        self.validateButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.validateButton.setObjectName("validateButton")
        self.itemNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.itemNameLabel.setGeometry(QtCore.QRect(20, 440, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.itemNameLabel.setFont(font)
        self.itemNameLabel.setScaledContents(False)
        self.itemNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.itemNameLabel.setObjectName("itemNameLabel")
        self.itemURLLabel = QtWidgets.QLabel(self.centralwidget)
        self.itemURLLabel.setGeometry(QtCore.QRect(20, 480, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.itemURLLabel.setFont(font)
        self.itemURLLabel.setScaledContents(False)
        self.itemURLLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.itemURLLabel.setObjectName("itemURLLabel")
        self.productList = QtWidgets.QListWidget(self.centralwidget)
        self.productList.setGeometry(QtCore.QRect(20, 21, 471, 351))
        self.productList.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.productList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.productList.setViewMode(QtWidgets.QListView.ListMode)
        self.productList.setObjectName("productList")
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(420, 380, 71, 23))
        self.removeButton.setObjectName("removeButton")
        self.detailsFrame = QtWidgets.QFrame(self.centralwidget)
        self.detailsFrame.setGeometry(QtCore.QRect(530, 20, 241, 431))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.PlaceholderText, brush)
        self.detailsFrame.setPalette(palette)
        self.detailsFrame.setAutoFillBackground(True)
        self.detailsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailsFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.detailsFrame.setObjectName("detailsFrame")
        self.productNameLabel = QtWidgets.QLabel(self.detailsFrame)
        self.productNameLabel.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.productNameLabel.setFont(font)
        self.productNameLabel.setObjectName("productNameLabel")
        self.amazonUrlLabel = QtWidgets.QLabel(self.detailsFrame)
        self.amazonUrlLabel.setGeometry(QtCore.QRect(10, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.amazonUrlLabel.setFont(font)
        self.amazonUrlLabel.setObjectName("amazonUrlLabel")
        self.productName = QtWidgets.QLabel(self.detailsFrame)
        self.productName.setGeometry(QtCore.QRect(10, 40, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.productName.sizePolicy().hasHeightForWidth())
        self.productName.setSizePolicy(sizePolicy)
        self.productName.setMaximumSize(QtCore.QSize(221, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.productName.setFont(font)
        self.productName.setText("")
        self.productName.setTextFormat(QtCore.Qt.AutoText)
        self.productName.setWordWrap(True)
        self.productName.setObjectName("productName")
        self.amazonUrl = QtWidgets.QLabel(self.detailsFrame)
        self.amazonUrl.setGeometry(QtCore.QRect(10, 130, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.amazonUrl.sizePolicy().hasHeightForWidth())
        self.amazonUrl.setSizePolicy(sizePolicy)
        self.amazonUrl.setMaximumSize(QtCore.QSize(221, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.amazonUrl.setFont(font)
        self.amazonUrl.setText("")
        self.amazonUrl.setTextFormat(QtCore.Qt.AutoText)
        self.amazonUrl.setWordWrap(True)
        self.amazonUrl.setObjectName("amazonUrl")
        self.priceLabel = QtWidgets.QLabel(self.detailsFrame)
        self.priceLabel.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.priceLabel.setFont(font)
        self.priceLabel.setObjectName("priceLabel")
        self.price = QtWidgets.QLabel(self.detailsFrame)
        self.price.setGeometry(QtCore.QRect(10, 220, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMaximumSize(QtCore.QSize(221, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.price.setFont(font)
        self.price.setText("")
        self.price.setTextFormat(QtCore.Qt.AutoText)
        self.price.setWordWrap(True)
        self.price.setObjectName("price")
        self.avgPriceLabel = QtWidgets.QLabel(self.detailsFrame)
        self.avgPriceLabel.setGeometry(QtCore.QRect(10, 270, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.avgPriceLabel.setFont(font)
        self.avgPriceLabel.setObjectName("avgPriceLabel")
        self.avgPrice = QtWidgets.QLabel(self.detailsFrame)
        self.avgPrice.setGeometry(QtCore.QRect(10, 310, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.avgPrice.sizePolicy().hasHeightForWidth())
        self.avgPrice.setSizePolicy(sizePolicy)
        self.avgPrice.setMaximumSize(QtCore.QSize(221, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.avgPrice.setFont(font)
        self.avgPrice.setText("")
        self.avgPrice.setTextFormat(QtCore.Qt.AutoText)
        self.avgPrice.setWordWrap(True)
        self.avgPrice.setObjectName("avgPrice")
        self.serverFrame = QtWidgets.QFrame(self.centralwidget)
        self.serverFrame.setGeometry(QtCore.QRect(530, 460, 241, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.PlaceholderText, brush)
        self.serverFrame.setPalette(palette)
        self.serverFrame.setAutoFillBackground(True)
        self.serverFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serverFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.serverFrame.setObjectName("serverFrame")
        self.statusLabel = QtWidgets.QLabel(self.serverFrame)
        self.statusLabel.setGeometry(QtCore.QRect(10, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.currentStatus = QtWidgets.QLabel(self.serverFrame)
        self.currentStatus.setGeometry(QtCore.QRect(120, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentStatus.setFont(font)
        if searchFile(2) == "":
            self.currentStatus.setText("Disconnected")
        else:
            self.currentStatus.setText("Connected")
        self.currentStatus.setObjectName("currentStatus")
        self.ipLabel = QtWidgets.QLabel(self.serverFrame)
        self.ipLabel.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ipLabel.setFont(font)
        self.ipLabel.setObjectName("ipLabel")
        self.currentIP = QtWidgets.QLabel(self.serverFrame)
        self.currentIP.setGeometry(QtCore.QRect(70, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentIP.setFont(font)
        self.currentIP.setText(searchFile(2))
        self.currentIP.setObjectName("currentIP")
        self.updateButton = QtWidgets.QPushButton(self.serverFrame)
        self.updateButton.setGeometry(QtCore.QRect(160, 60, 71, 23))
        self.updateButton.clicked.connect(self.updateLabel)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.updateButton.setFont(font)
        self.updateButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.updateButton.setObjectName("updateButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        mainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(mainWindow)
        self.actionConnect.setIconVisibleInMenu(False)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(mainWindow)
        self.actionDisconnect.setIconVisibleInMenu(False)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionHelp = QtWidgets.QAction(mainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPrefrences = QtWidgets.QAction(mainWindow)
        self.actionPrefrences.setObjectName("actionPrefrences")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionDisconnect)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionPrefrences)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AmazonWatch"))
        self.confirmButton.setStatusTip(_translate(
            "mainWindow", "Add this product to tracking list."))
        self.confirmButton.setText(_translate("mainWindow", "Confirm"))
        self.itemName.setStatusTip(_translate(
            "mainWindow", "Name of the product to help you keep organised. Does not get sent to server."))
        self.itemName.setPlaceholderText(_translate(
            "mainWindow", "Amazon Echo Dot 3rd Gen"))
        self.itemURL.setStatusTip(_translate(
            "mainWindow", "Amazon Link to the item. Gets sent to server."))
        self.itemURL.setPlaceholderText(_translate(
            "mainWindow", "https://www.amazon.co.uk/Echo-Dot-3rd-Gen-Charcoal/dp/B07PJV3JPR/"))
        self.validateButton.setStatusTip(_translate(
            "mainWindow", "Check if the URL entered is valid."))
        self.validateButton.setText(_translate("mainWindow", "Validate URL"))
        self.itemNameLabel.setStatusTip(_translate(
            "mainWindow", "Name of the product to help you keep organised. Does not get sent to server."))
        self.itemNameLabel.setText(_translate("mainWindow", "Product Name"))
        self.itemURLLabel.setStatusTip(_translate(
            "mainWindow", "Amazon Link to the item. Gets sent to server."))
        self.itemURLLabel.setText(_translate("mainWindow", "Amazon URL"))
        self.productList.setStatusTip(_translate("mainWindow", "Product List"))
        self.removeButton.setStatusTip(_translate(
            "mainWindow", "Delete a product from the list."))
        self.removeButton.setText(_translate("mainWindow", "Delete"))
        self.detailsFrame.setStatusTip(
            _translate("mainWindow", "Product Details"))
        self.productNameLabel.setText(
            _translate("mainWindow", "Product Name:"))
        self.amazonUrlLabel.setText(_translate("mainWindow", "Amazon URL:"))
        self.priceLabel.setText(_translate("mainWindow", "Current Price:"))
        self.avgPriceLabel.setText(_translate("mainWindow", "Average Price:"))
        self.serverFrame.setStatusTip(
            _translate("mainWindow", "Server Status"))
        self.statusLabel.setText(_translate(
            "mainWindow", "Connection Status:"))
        self.ipLabel.setText(_translate("mainWindow", "Server IP:"))
        self.updateButton.setStatusTip(_translate(
            "mainWindow", "Add this product to tracking list."))
        self.updateButton.setText(_translate("mainWindow", "Update"))
        self.menuFile.setTitle(_translate("mainWindow", "Connect"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings"))
        self.actionConnect.setText(_translate(
            "mainWindow", "Connect to Server"))
        self.actionConnect.setStatusTip(_translate(
            "mainWindow", "New connection to server."))
        self.actionConnect.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionConnect.triggered.connect(self.openConnectWindow)
        self.actionDisconnect.setText(_translate("mainWindow", "Disconnect"))
        self.actionDisconnect.setStatusTip(
            _translate("mainWindow", "Disconnect from server."))
        self.actionDisconnect.triggered.connect(self.deleteData)
        self.actionDisconnect.setShortcut(_translate("mainWindow", "Ctrl+X"))
        self.actionHelp.setText(_translate("mainWindow", "Help"))
        self.actionHelp.setStatusTip(_translate("mainWindow", "Need help?"))
        self.actionHelp.setShortcut(_translate("mainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionAbout.triggered.connect(self.openAboutWindow)
        self.actionAbout.setStatusTip(
            _translate("mainWindow", "More information."))
        self.actionPrefrences.setText(_translate("mainWindow", "Prefrences"))

    def updateLabel(self, mainWindow):
        currentIP = searchFile(2)
        if currentIP != "":
            self.currentStatus.setText("Connected")
            self.currentIP.setText(currentIP)
        else:
            self.currentStatus.setText("Disconnected")
            self.currentIP.setText(currentIP)

    def deleteData(self, mainWindow):
        deleteFile(2)
        deleteFile(3)
        Ui_mainWindow.updateLabel(self, mainWindow)


def startUi():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
